name: Generate VSIX Package and Create Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: yarn install

      - name: Get package version
        run:
          echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")"
          >> $GITHUB_ENV

      - name: Compile extension
        run: yarn run compile

      - name: Package extension with VSCE
        run: npx vsce package --out dist
        env:
          VSCE_PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v2
        with:
          name: zayat-utilities-vsix
          path: "dist/*.vsix"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.PACKAGE_VERSION }}
          release_name: Release v${{ env.PACKAGE_VERSION }}
          body: |
            Release for version v${{ env.PACKAGE_VERSION }}
          draft: false
          prerelease: false
